FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y \
    python3.14 \
    python3.14-venv \
    python3.14-dev \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN python3.14 -m ensurepip && \
    python3.14 -m pip install --upgrade pip

RUN ln -sf /usr/bin/python3.14 /usr/bin/python3 && \
    ln -sf /usr/bin/python3.14 /usr/bin/python

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN pip3 install uv && \
    uv pip install --system -r pyproject.toml

COPY src/ ./src/
COPY exceptions.py ./
COPY alembic.ini ./
COPY migrations/ ./migrations/

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--workers 2"]
